### ISSUE TITLE
edit build

### ISSUE THREAD

**Issue by ignipae** [Smux/dauntless-build-collection#11]
it should be possible to edit a build afterwards -> title, weaponType, url and description

**Comment by lasdem** [comment]
You probably should not be able to edit the URL or weapon type if there are already votes on the build. 
Or the votes should be lost after such an edit. 
But I think it would be really helpful to edit the Title and add a Description.

**Comment by ignipae** [comment]
@lasdem 
Indeed! I was thinking about the same, that votes should be resetted after changing the url (after warning the user upfront)

A description feature is already planned #9 

Thanks for your feedback!

**Comment by ignipae** [comment]
Implemented
