### ISSUE TITLE
Missing Functionality

### ISSUE THREAD

**Issue by ignipae** [Smux/dauntless-build-collection#30]
--- core
- [x] Add Builds navigation to global header (Builds, My Builds, Favorite Builds)
- [x] add delete possibility to list item (owner only)
- [x] implement rating on list item
- [x] add lastModified to build & show it accordingly
- [x] sorting on builds list
- [x] filter for weapon type
- [x] mails -> password reset
- [x] paging
- [x] no data text
- [x] data validation
- [x] tags
- [x] use favicon
- [x] clear database
- [x] change mongodb db user

--- other
- [ ] discord link

**Comment by ignipae** [comment]
tags:
![image](https://user-images.githubusercontent.com/4704905/59969853-8acf1a80-9558-11e9-985f-2a3a6e88e7ac.png)

**Comment by Smux** [comment]
Needed:
- [ ] Direct URL for create should check for authentication
- [ ] Sitemap for google
- [ ] Rating on user screen
