### ISSUE TITLE
Reloading after voting

### ISSUE THREAD

**Issue by Smux** [Smux/dauntless-build-collection#32]
Should we reload the list to recalculate the rating stats for the build?
Let's discuss this.

**Comment by Smux** [comment]
Implemented the reloading. We have to make sure to pass all query parameters to the backend again.

**Comment by Smux** [comment]
Paging and weapon type filter has to be implemented for this.

**Comment by ignipae** [comment]
done ;) just trigger _loadBuilds() without any params
