### ISSUE TITLE
Discuss dauntless builder integration

### ISSUE THREAD

**Issue by Smux** [Smux/dauntless-build-collection#37]
Dauntless builder could reference our page [Share build on Dauntless Build Collection]. This leads to our create page with the hashid prefilled for the build.

**Comment by ignipae** [comment]
During creation passover the query property: ?hash=<hash> => this will prefill the url of the dauntless builder

**Comment by ignipae** [comment]
@Smux please provide this approach to the Dauntless Builder :)

**Comment by Smux** [comment]
finalized
