### ISSUE TITLE
Says URL is not valid but im coming straight from dauntless builder

### ISSUE THREAD

**Issue by Hatter000** [Smux/dauntless-build-collection#66]
when i try to post to Dauntless build collection with one of my builds it says the url is not valid but i came straight from dauntless builder. Build URL: https://www.dauntless-builder.com/b/gPUWwF0Cm0szvfNTvT5TWTKTNTLPiACXeH71uMCRat43CjC01HWtwCrLs4CPX

**Comment by Nacaroost** [comment]
i have the same probleme and after making some test i found is all build with malkarion piece can't be add

**Comment by Smux** [comment]
@Hatter000 The issue is fixed now, please try again :)
