### ISSUE TITLE
Think about view and rating restriction system

### ISSUE THREAD

**Issue by Smux** [Smux/dauntless-build-collection#8]
We should think about how we want to restrict who can rate and whether the view counter that we possibly offer is incremented. By each view, only by view per IP, etc.

**Comment by ignipae** [comment]
views should be counted by session -> user cookie.
Rating should be allowed only for logged in users and each user can only upvote a build or remove this upvote.

Downvotes are too toxic imo

**Comment by Smux** [comment]
rating is also done
