### ISSUE TITLE
build description missing

### ISSUE THREAD

**Issue by ignipae** [Smux/dauntless-build-collection#9]
additionally, the description will be markdown text

**Comment by Smux** [comment]
description will be available with a rich text editor, markdown is maybe too confusing

**Comment by guidez** [comment]
Was gonna add this as a feature request, but would like a summary/description area for people to explain why their build is good or how it's supposed to be run.

**Comment by Smux** [comment]
@guidez We will defnitely implement this for the next release, thank you!

**Comment by ignipae** [comment]
Implemented
